services:
  app:
    networks:
      default:
      devvault-edge:
        aliases:
          - devvault-app

  frontend:
    networks:
      default:
      devvault-edge:
        aliases:
          - devvault-frontend

networks:
  devvault-edge:
    external: true
    name: devvault-edge
