services:
  app:
    networks:
      default:
      marketboard:
        aliases:
          - devvault-app

  frontend:
    networks:
      default:
      marketboard:
        aliases:
          - devvault-frontend

networks:
  marketboard:
    external: true
    name: marketboard_marketboard
